package eventsapp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x16102584
 */
public class EventsGUI extends javax.swing.JFrame {

    /**
     * Creates new form EventsGUI
     */
    public EventsGUI() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aviD = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        croD = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        kinD = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        thoD = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        allD = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        selectionPane = new javax.swing.JPanel();
        viewEvents = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aviB = new javax.swing.JButton();
        croB = new javax.swing.JButton();
        kinB = new javax.swing.JButton();
        thoB = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();
        typL = new javax.swing.JLabel();
        whoL = new javax.swing.JLabel();
        locL = new javax.swing.JLabel();
        datL = new javax.swing.JLabel();
        whoF = new javax.swing.JTextField();
        datF = new javax.swing.JTextField();
        typB = new javax.swing.JComboBox<>();
        locB = new javax.swing.JComboBox<>();
        addConfirm = new javax.swing.JButton();
        clearConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        aviD.setMaximumSize(new java.awt.Dimension(1000, 800));
        aviD.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("AVIVA STADIUM EVENTS");

        javax.swing.GroupLayout aviDLayout = new javax.swing.GroupLayout(aviD.getContentPane());
        aviD.getContentPane().setLayout(aviDLayout);
        aviDLayout.setHorizontalGroup(
            aviDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aviDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        aviDLayout.setVerticalGroup(
            aviDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aviDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(511, Short.MAX_VALUE))
        );

        croD.setMaximumSize(new java.awt.Dimension(1000, 800));
        croD.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("CROKE PARK EVENTS");

        javax.swing.GroupLayout croDLayout = new javax.swing.GroupLayout(croD.getContentPane());
        croD.getContentPane().setLayout(croDLayout);
        croDLayout.setHorizontalGroup(
            croDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(croDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(717, Short.MAX_VALUE))
        );
        croDLayout.setVerticalGroup(
            croDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(croDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(622, Short.MAX_VALUE))
        );

        kinD.setMaximumSize(new java.awt.Dimension(1000, 800));
        kinD.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("KINGSPAN STADIUM");

        javax.swing.GroupLayout kinDLayout = new javax.swing.GroupLayout(kinD.getContentPane());
        kinD.getContentPane().setLayout(kinDLayout);
        kinDLayout.setHorizontalGroup(
            kinDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kinDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(805, Short.MAX_VALUE))
        );
        kinDLayout.setVerticalGroup(
            kinDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kinDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(667, Short.MAX_VALUE))
        );

        thoD.setLocationByPlatform(true);
        thoD.setMaximumSize(new java.awt.Dimension(1000, 800));
        thoD.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setText("THOMOND PARK EVENTS");

        javax.swing.GroupLayout thoDLayout = new javax.swing.GroupLayout(thoD.getContentPane());
        thoD.getContentPane().setLayout(thoDLayout);
        thoDLayout.setHorizontalGroup(
            thoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thoDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        thoDLayout.setVerticalGroup(
            thoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thoDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(548, Short.MAX_VALUE))
        );

        allD.setTitle("alld");
        allD.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setText("All Events");

        javax.swing.GroupLayout allDLayout = new javax.swing.GroupLayout(allD.getContentPane());
        allD.getContentPane().setLayout(allDLayout);
        allDLayout.setHorizontalGroup(
            allDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        allDLayout.setVerticalGroup(
            allDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectionPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        viewEvents.setText("View All Events");
        viewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEventsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("List Events");

        jLabel3.setText("Load events by locations listed below.");

        aviB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        aviB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventsapp/aviva.jpg"))); // NOI18N
        aviB.setText("AVIVA STADIUM");
        aviB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aviBActionPerformed(evt);
            }
        });

        croB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        croB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventsapp/croke.jpg"))); // NOI18N
        croB.setText("CROKE PARK");
        croB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croBActionPerformed(evt);
            }
        });

        kinB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kinB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventsapp/kingspan.jpg"))); // NOI18N
        kinB.setText("KINGSPAN STADIUM");
        kinB.setToolTipText("");
        kinB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinBActionPerformed(evt);
            }
        });

        thoB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        thoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventsapp/thomond.jpg"))); // NOI18N
        thoB.setText("THOMOND PARK");
        thoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectionPaneLayout = new javax.swing.GroupLayout(selectionPane);
        selectionPane.setLayout(selectionPaneLayout);
        selectionPaneLayout.setHorizontalGroup(
            selectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPaneLayout.createSequentialGroup()
                .addGroup(selectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionPaneLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2))
                    .addGroup(selectionPaneLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3)))
                .addContainerGap(254, Short.MAX_VALUE))
            .addComponent(viewEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kinB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(croB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aviB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectionPaneLayout.setVerticalGroup(
            selectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(aviB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(croB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kinB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoB)
                .addGap(18, 18, 18)
                .addComponent(viewEvents)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        contentPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        typL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typL.setText("Type: ");

        whoL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whoL.setText("Who:");

        locL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        locL.setText("Location:");

        datL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datL.setText("Date:");
        datL.setToolTipText("");

        whoF.setText("Name");

        datF.setText("DD/MM/YYYY");

        typB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concert", "Match", "Exhibition", "Conference" }));
        typB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typBActionPerformed(evt);
            }
        });

        locB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Croke Park", "Aviva Stadium", "Kingspan Stadium", "Thomond Park" }));

        addConfirm.setText("Add Event");

        clearConfirm.setText("Clear Details");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add An Event:");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearConfirm))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPaneLayout.createSequentialGroup()
                                        .addComponent(datL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(datF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contentPaneLayout.createSequentialGroup()
                                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(locL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(typL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(whoL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(typB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(whoF)
                                            .addComponent(locB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typL)
                    .addComponent(typB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whoL)
                    .addComponent(whoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locL)
                    .addComponent(locB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datL)
                    .addComponent(datF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addConfirm)
                    .addComponent(clearConfirm))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEventsActionPerformed
        // TODO add your handling code here:
        
        allD.setVisible(true);
        aviD.setVisible(false);
        croD.setVisible(false);
        kinD.setVisible(false);
        thoD.setVisible(false);
    }//GEN-LAST:event_viewEventsActionPerformed

    private void typBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typBActionPerformed

    private void aviBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aviBActionPerformed
        // TODO add your handling code here:
        
        allD.setVisible(false);
        aviD.setVisible(true);
        croD.setVisible(false);
        kinD.setVisible(false);
        thoD.setVisible(false);
    }//GEN-LAST:event_aviBActionPerformed

    private void croBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croBActionPerformed
        // TODO add your handling code here:
        
        allD.setVisible(false);
        aviD.setVisible(false);
        croD.setVisible(true);
        kinD.setVisible(false);
        thoD.setVisible(false);
    }//GEN-LAST:event_croBActionPerformed

    private void kinBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinBActionPerformed
        // TODO add your handling code here:
        
        allD.setVisible(false);
        aviD.setVisible(false);
        croD.setVisible(false);
        kinD.setVisible(true);
        thoD.setVisible(false);
    }//GEN-LAST:event_kinBActionPerformed

    private void thoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoBActionPerformed
        // TODO add your handling code here:
        
        allD.setVisible(false);
        aviD.setVisible(false);
        croD.setVisible(false);
        kinD.setVisible(false);
        thoD.setVisible(true);
    }//GEN-LAST:event_thoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConfirm;
    private javax.swing.JDialog allD;
    private javax.swing.JButton aviB;
    private javax.swing.JDialog aviD;
    private javax.swing.JButton clearConfirm;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton croB;
    private javax.swing.JDialog croD;
    private javax.swing.JTextField datF;
    private javax.swing.JLabel datL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton kinB;
    private javax.swing.JDialog kinD;
    private javax.swing.JComboBox<String> locB;
    private javax.swing.JLabel locL;
    private javax.swing.JPanel selectionPane;
    private javax.swing.JButton thoB;
    private javax.swing.JDialog thoD;
    private javax.swing.JComboBox<String> typB;
    private javax.swing.JLabel typL;
    private javax.swing.JButton viewEvents;
    private javax.swing.JTextField whoF;
    private javax.swing.JLabel whoL;
    // End of variables declaration//GEN-END:variables
}
